#!/bin/bash
# Translate wm-common/ configs to Hyprland format
# Run this after modifying wm-common/ to update Hyprland configs

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

WM_COMMON="$HOME/.config/wm-common"
HYPR_DIR="$HOME/.config/hypr"

translate_colors() {
    log_info "Translating colors.conf to Hyprland format..."

    local input="$WM_COMMON/colors.conf"
    local output="$HYPR_DIR/colors.conf"

    if [[ ! -f "$input" ]]; then
        log_warn "wm-common/colors.conf not found, skipping"
        return
    fi

    cat > "$output" << 'HEADER'
# Gruvbox Material Dark - Hyprland format
# AUTO-GENERATED from wm-common/colors.conf by translate-hyprland.sh
# DO NOT EDIT DIRECTLY - edit wm-common/colors.conf instead

HEADER

    # Convert: set $varname #xxxxxx -> $varname = rgb(xxxxxx)
    while IFS= read -r line; do
        # Skip comments and empty lines (pass them through)
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "${line// }" ]]; then
            echo "$line" >> "$output"
            continue
        fi

        # Match: set $varname #xxxxxx
        if [[ "$line" =~ ^set[[:space:]]+\$([a-zA-Z_]+)[[:space:]]+\#([0-9a-fA-F]{6}) ]]; then
            local varname="${BASH_REMATCH[1]}"
            local color="${BASH_REMATCH[2]}"
            echo "\$$varname = rgb($color)" >> "$output"
        fi
    done < "$input"

    log_ok "Colors translated: $output"
}

translate_workspaces() {
    log_info "Generating workspaces.conf for Hyprland..."

    local output="$HYPR_DIR/workspaces.conf"

    cat > "$output" << 'EOF'
# Workspaces - Hyprland format
# AUTO-GENERATED by translate-hyprland.sh

# Switch to workspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Special workspaces (scratchpads)
workspace = special:dropdown, on-created-empty:kitty --class dropdown
workspace = special:ranger, on-created-empty:kitty --class ranger-scratch -e ranger
EOF

    log_ok "Workspaces generated: $output"
}

show_keybinding_note() {
    log_info "Note: Hyprland keybindings are manually maintained in:"
    echo "  $HYPR_DIR/keybindings.conf"
    echo ""
    echo "Key differences from i3/Sway:"
    echo "  - bindsym \$mod+X action  ->  bind = \$mod, X, action"
    echo "  - focus left/right/up/down  ->  movefocus, l/r/u/d"
    echo "  - move left/right/up/down   ->  movewindow, l/r/u/d"
    echo "  - mode \"resize\"           ->  submap = resize"
    echo ""
    echo "If you add new keybindings to wm-common/keybindings.conf,"
    echo "you must manually add them to hypr/keybindings.conf as well."
}

main() {
    log_info "Starting Hyprland config translation..."

    if [[ ! -d "$WM_COMMON" ]]; then
        log_error "wm-common/ not found at $WM_COMMON"
        log_info "Run 'sync-wm.sh shared --install' first to create it"
        exit 1
    fi

    mkdir -p "$HYPR_DIR"

    translate_colors
    translate_workspaces
    show_keybinding_note

    log_ok "Hyprland translation complete!"
}

main "$@"
