"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
[󰀵](bg:color_orange fg:color_fg_dark)\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$python\
$nodejs\
$rust\
$golang\
$c\
$cpp\
$java\
$kotlin\
$haskell\
$php\
$ruby\
$lua\
$zig\
$deno\
$bun\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$cmd_duration\
$jobs\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.neon_tokyo]
color_fg0     = '#c0caf5'
color_fg_dark = '#1a1b26'
color_bg1     = '#16161e'
color_bg3     = '#292e42'
color_blue    = '#7aa2f7'
color_aqua    = '#2ac3de'
color_green   = '#9ece6a'
color_orange  = '#ff9e64'
color_purple  = '#bb9af7'
color_red     = '#f7768e'
color_yellow  = '#e0af68'

[palettes.neon_synthwave]
color_fg0     = '#f1f5ff'
color_fg_dark = '#0d0717'
color_bg1     = '#150d24'
color_bg3     = '#241734'
color_blue    = '#9d72ff'
color_aqua    = '#08f7fe'
color_green   = '#21f6a3'
color_orange  = '#fe53bb'
color_purple  = '#c084fc'
color_red     = '#ff3caa'
color_yellow  = '#f5d300'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg_dark = '#282828'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_macchiato]
color_fg0 = '#cad3f5'
color_fg_dark = '#181926'
color_bg1 = '#1e2030'
color_bg3 = '#363a4f'
color_blue = '#8aadf4'
color_aqua = '#8bd5ca'
color_green = '#a6da95'
color_orange = '#f5a97f'
color_purple = '#c6a0f6'
color_red = '#ed8796'
color_yellow = '#eed49f'

[palettes.catppuccin_latte]
color_fg0 = '#4c4f69'
color_fg_dark = '#4c4f69'
color_bg1 = '#e6e9ef'
color_bg3 = '#ccd0da'
color_blue = '#1e66f5'
color_aqua = '#179299'
color_green = '#40a02b'
color_orange = '#fe640b'
color_purple = '#8839ef'
color_red = '#d20f39'
color_yellow = '#df8e1d'

[palettes.catppuccin_frappe]
color_fg0 = '#c6d0f5'
color_fg_dark = '#232634'
color_bg1 = '#292c3c'
color_bg3 = '#414559'
color_blue = '#8caaee'
color_aqua = '#81c8be'
color_green = '#a6d189'
color_orange = '#ef9f76'
color_purple = '#ca9ee6'
color_red = '#e78284'
color_yellow = '#e5c890'

[palettes.catppuccin_mocha]
color_fg0 = '#cdd6f4'
color_fg_dark = '#11111b'
color_bg1 = '#181825'
color_bg3 = '#313244'
color_blue = '#89b4fa'
color_aqua = '#94e2d5'
color_green = '#a6e3a1'
color_orange = '#fab387'
color_purple = '#cba6f7'
color_red = '#f38ba8'
color_yellow = '#f9e2af'

[os]
disabled = false
style = "bg:color_orange fg:color_fg_dark"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg_dark"
style_root = "bg:color_orange fg:color_fg_dark"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg_dark bg:color_yellow"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " 󰌾"
read_only_style = "fg:color_red bg:color_yellow"
before_repo_root_style = "fg:color_fg_dark bg:color_yellow"
repo_root_style = "bold fg:color_fg_dark bg:color_yellow"
repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg_dark bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg_dark bg:color_aqua)]($style)'
conflicted = '=${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
up_to_date = ''
untracked = '?${count} '
stashed = '≡${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '✘${count} '

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg_dark bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)( $virtualenv) ](fg:color_fg_dark bg:color_blue)]($style)'
detect_folders = ['.venv']
python_binary = ['python3', 'python']

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[cmd_duration]
min_time = 500
show_milliseconds = false
style = "fg:color_fg0 bg:color_bg1"
format = '[ 󰔚 $duration ]($style)'

[jobs]
symbol = "󰜎 "
number_threshold = 1
style = "fg:color_fg0 bg:color_bg1"
format = '[ $symbol$number ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
